### ISSUE TITLE
Function [cluster] not working after upgrading from 3.5.8 to 4.0

### ISSUE THREAD

**Issue by julianzz98** [hupe13/extensions-leaflet-map#12]
First of all, thank you for your work and providing this great plugin to the community!

After I manually updated the plugin from version 3.5.8 to 4.0, the function [cluster] seems to be not working anymore. I tried different configurations using the provided options with no results.

The code in my HTML element looks like this (formatted and modified the content for readability):
```
[leaflet-map lat=51.1657 lng=10.4515 zoom=6 width=800px height=800px]
[leaflet-geojson src="path/to/example.json"]<b>Example:</b> {Example}<br> [/leaflet-geojson]
[hover geojsontooltip="{Test}"]
[cluster]
[zoomhomemap]
```
Are there any changes that I am missing? The changelog did not mention direct changes to [cluster] function.

Would appreciate a response!

**Comment by hupe13** [comment]
I can't confirm this. Maybe the zoom is to high, zoom out the map. Do the marker cluster then? Or set you `disableClusteringAtZoom = 0`? Then is clustering forbidden.

**Comment by julianzz98** [comment]
The clustering is not happening, regardless of the zoom level. `disableClusteringAtZoom = 0` is not set. Next step would be to manually downgrade the plugin, for this I still need to increase the file size limit...

**Comment by julianzz98** [comment]
Okay after manually downgrading to the previous version (GitHub ZIP), the cluster function is working again.

Version 3.5.8:
![image](https://github.com/hupe13/extensions-leaflet-map-github/assets/74777462/f077d1b2-a1b7-4c01-bca2-343e23178f0e)

Version 4.0:
![image](https://github.com/hupe13/extensions-leaflet-map-github/assets/74777462/a34e20f4-a7f2-48ef-8194-775ecf7022c4)

**Comment by julianzz98** [comment]
Could the PHP version cause a problem? We are still using 7.4, even though the requirements of the plugin state PHP version 7.4 ...

**Comment by hupe13** [comment]
php 7.4 is old, you should upgrade. But this seems not the problem. Install https://de.wordpress.org/plugins/query-monitor/ to see any errors. Open the developer console to see Javascript or other errors. 
Maybe the geojson file has a problem. Keine Ahnung. My [mail address](https://leafext.de/doku/about/).

**Comment by julianzz98** [comment]
Danke! Will report back.

**Comment by hupe13** [comment]
Or a cache plugin?

**Comment by julianzz98** [comment]
Moin! I finally had the chance to upgrade the PHP version from 7.4 to 8.3 and reinstalled the plugin in the version 4.0. The cluster function now works again. 

Therefore I would suggest you pinpoint the current minimum requirement of the PHP version that the plugin needs now and update your listed requirements accordingly.

Closing this issue! Thanks again for the response!

**Comment by hupe13** [comment]
Thank you for testing. I no longer have access to php 7.4 anywhere, so I installed it on my local PC (Windows) again and only called up one page and it didn't give any error. That's why the php 7.4 error would have been interesting for me.

**Comment by julianzz98** [comment]
That is my bad. Forgot about checking the error message beforehand...

**Comment by hupe13** [comment]
There are [compatibility checks](https://github.com/PHPCompatibility/PHPCompatibilityWP) available. These show problems with php 7.2 or earlier, but no problems with 7.4. 
Aber egal, schön, dass es nun läuft und auch aktuell ist.

**Comment by hupe13** [comment]
Ich habe soeben einen (diesen) [Bug](https://wordpress.org/support/topic/marker-cluster-options-have-no-effect/) gefunden.

**Comment by julianzz98** [comment]
Und? Was war jetzt der Fehler?

**Comment by hupe13** [comment]
Ich habe Parameter als "string" statt als "int" der Funktion übergeben. Ich hatte doch was geändert von 3.5.8 zu 4.0: Ich habe versucht, das Inline-Javascript auszulagern.

**Comment by julianzz98** [comment]
Ok, dann hat sich das ja fix gelöst! Danke für den tollen Support!

**Comment by hupe13** [comment]
Na wenn 2 sich beschweren ... Und dort hatte ich auch einen Link zur Seite, das hilft.
