### ISSUE TITLE
Lower required PHP version

### ISSUE THREAD

**Issue by davidkopp** [hupe13/extensions-leaflet-map#3]
Currently the plugin requires the PHP version 7.4. However I think for this simple plugin that's not required. Currently 30 % of the Wordpress sites are still using 7.3, 18% using 7.2 ([Wordpress Stats](https://wordpress.org/about/stats/)).
I have a website that runs PHP 7.3 and I can't upgrade on my own. Would be great to set the required PHP version to a version that's actually required.

**Comment by hupe13** [comment]
I have changed the readme.txt only.

**Comment by davidkopp** [comment]
I mean it's still possible to install the plugin manually (tested on a site with PHP 7.3). However it's not possible to install the plugin via the official Wordpress plugin site. Therefore I think it would be good to lower the requirements to the actual required PHP version.

**Comment by hupe13** [comment]
Entschuldigung. Ich versuchte heute das Wordpress SVN zu verstehen. Dort habe ich es geändert, nicht hier.
I'm sorry. Today I tried to understand the Wordpress SVN. I changed it there, not here.
