### ISSUE TITLE
Grouping leaflet-marker does not work me

### ISSUE THREAD

**Issue by niklasberlin** [hupe13/extensions-leaflet-map#5]
Hello, first of all thanks for this awesome plugin.

I have the following issue: when i try to create a map with the example code found here: https://leafext.de/en/grouping/markers/ i can see a map with three markers as in the example (ok one the images is missing but that is just because i haven't uploaded the icon to my wordpress). But the main Problem is that the group selection in the top right corner is missing (the picture below).

I have tried that on a dev install of wordpress to rule out problem with other plugins, i used the following paramters:
PHP 8.2.0
Wordpress 6.1.1

Pugins:
only "Leaflet Map" in Version 3.3.0 and "Extensions for Leaflet Map" in Version 3.3.3 (both installed via the build-in search function from the worpress repository)

Theme: default (Twenty Twenty Three)

![image](https://user-images.githubusercontent.com/2325269/222785585-67d3f024-dde8-4bd0-b04c-2e108f1fc6b6.png)

i also tried to add additional markes after the [leaflet-optiongroup ..] shortcut to check if the option group still ins scope for the map and the addional markes get rendered succesfully, but the optiongroup is still missing

I hope that the informations i have provided are useful, please let me know if you need additional informations to reproduce the error

**Comment by hupe13** [comment]
Have all markers the option "iconClass=...."? Is it the same shortcode as on the example page?

**Comment by niklasberlin** [comment]
yes they all have the "iconClass" Attribute and it is a full copy of the example code (only change is the additional marker after the option group, but even when I remove this and have a 1to1 copy of the example code it does not work):
![image](https://user-images.githubusercontent.com/2325269/222795036-b38d87f3-ec05-4f25-807b-fe73bc79e228.png)

**Comment by hupe13** [comment]
I tested it, it seems to be a bug, the new version (3.4) will work as expected. It is on Github.

**Comment by niklasberlin** [comment]
Thank you for the tip, i had only looked at the releases on github and there was only an older version (3.2.2), now i cloned the repo and it worked as expected, thank you.

**Comment by hupe13** [comment]
Release and tagging - I am not correct in doing so. Can you test please the newest [tag](https://github.com/hupe13/extensions-leaflet-map-github/tags)?
