### ISSUE TITLE
CORS issues loading leaflet-plugins handlers from CDN

### ISSUE THREAD

**Issue by thejeshgn** [hupe13/extensions-leaflet-map#9]
All the JavaScript on my site are loaded from a CDN.  So many `leaflet-plugins` which are loaded dynamically have CORS issues and don't load. For example

* <cdn_domain>/wp-content/plugins/extensions-leaflet-map/leaflet-plugins/leaflet-elevation-2.4.0/src/handlers/speed.js
* <cdn_domain>/wp-content/plugins/extensions-leaflet-map/leaflet-plugins/leaflet-elevation-2.4.0/src/handlers/slope.js
* <cdn_domain>/wp-content/plugins/extensions-leaflet-map/leaflet-plugins/leaflet-gesture-handling-1.4.4/dist/locales/en.js

Should there be option to load inline?

**Comment by hupe13** [comment]
When I submitted my plugin to WordPress, I was asked to 

> Please remove external dependencies from your plugin and, if possible, include all files within the plugin (that is not called remotely).

That's why they are included in the plugin.

**Comment by hupe13** [comment]
What is the error message? Can you adapt the rules in server config or .htaccess?

**Comment by thejeshgn** [comment]
Thank you @hupe13 

Let me try couple of things and get back to you with more details.

**Comment by hupe13** [comment]
I close this. Feel free to come back, if the problem persists.
